version: 2.1

executors:
  python-executor:
    docker:
      - image: cimg/python:3.9  # Official CircleCI Python image
    working_directory: ~/repo

jobs:
  test:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            python -m pip install --upgrade pip
            pip install -r requirements.txt
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            pytest _test.py

workflows:
  ci-workflow:
    jobs:
      - test
